
package windows;

import java.sql.*;
import classes.Connection_DB;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class Delete_Users extends javax.swing.JFrame {

  String user = "", user_update = "";
  int ID;
  boolean flag = false;

  public Delete_Users() {
    initComponents();
    user = Login.user;
    user_update = Manage_Users.user_update;

    setSize(623, 303);
    setResizable(false);
    setTitle("User information " + user_update + " - " + user + " session");
    setLocationRelativeTo(null);

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
    Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
        lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
    lbl_wallpaper.setIcon(icono);
    this.repaint();

    lbl_Titulo.setText("User information " + user_update);

  }

  @Override
  public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
    return retValue;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    STATUS = new javax.swing.ButtonGroup();
    lbl_Titulo = new javax.swing.JLabel();
    jLabel_Name = new javax.swing.JLabel();
    txt_Name = new javax.swing.JTextField();
    jLabel_Email = new javax.swing.JLabel();
    txt_mail = new javax.swing.JTextField();
    jLabel_Phone = new javax.swing.JLabel();
    txt_Phone = new javax.swing.JTextField();
    jLabel_Username = new javax.swing.JLabel();
    txt_Username = new javax.swing.JTextField();
    jLabel_Status = new javax.swing.JLabel();
    jLabel_Registered = new javax.swing.JLabel();
    btn_Eliminar = new javax.swing.JButton();
    txt_Registered = new javax.swing.JTextField();
    txt_Status = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    btn_SearchID = new javax.swing.JButton();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lbl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    lbl_Titulo.setForeground(new java.awt.Color(255, 255, 255));
    lbl_Titulo.setText("User Information");
    getContentPane().add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

    jLabel_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Name.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Name.setText("Name:");
    getContentPane().add(jLabel_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    txt_Name.setBackground(new java.awt.Color(93, 93, 212));
    txt_Name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Name.setForeground(new java.awt.Color(255, 255, 255));
    txt_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

    jLabel_Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Email.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Email.setText("Email:");
    getContentPane().add(jLabel_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

    txt_mail.setBackground(new java.awt.Color(93, 93, 212));
    txt_mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_mail.setForeground(new java.awt.Color(255, 255, 255));
    txt_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_mail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

    jLabel_Phone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Phone.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Phone.setText("Phone:");
    getContentPane().add(jLabel_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

    txt_Phone.setBackground(new java.awt.Color(93, 93, 212));
    txt_Phone.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Phone.setForeground(new java.awt.Color(255, 255, 255));
    txt_Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Phone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

    jLabel_Username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Username.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Username.setText("Username:");
    getContentPane().add(jLabel_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

    txt_Username.setBackground(new java.awt.Color(93, 93, 212));
    txt_Username.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Username.setForeground(new java.awt.Color(255, 255, 255));
    txt_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

    jLabel_Status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Status.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Status.setText("Status:");
    getContentPane().add(jLabel_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

    jLabel_Registered.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Registered.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Registered.setText("Registered by:");
    getContentPane().add(jLabel_Registered, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

    btn_Eliminar.setBackground(new java.awt.Color(93, 93, 212));
    btn_Eliminar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
    btn_Eliminar.setText("Delete User");
    btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_EliminarActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 35));

    txt_Registered.setBackground(new java.awt.Color(93, 93, 212));
    txt_Registered.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Registered.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Registered.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Registered, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

    txt_Status.setBackground(new java.awt.Color(93, 93, 212));
    txt_Status.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Status.setForeground(new java.awt.Color(255, 255, 255));
    txt_Status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Status.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 210, -1));

    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Creado por Tony ©");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

    btn_SearchID.setBackground(new java.awt.Color(93, 93, 212));
    btn_SearchID.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btn_SearchID.setForeground(new java.awt.Color(255, 255, 255));
    btn_SearchID.setText("Search");
    btn_SearchID.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_SearchIDActionPerformed(evt);
      }
    });
    getContentPane().add(btn_SearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 210, 35));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 310));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_SearchIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_Eliminar1ActionPerformed
    ID = Integer.parseInt(JOptionPane.showInputDialog("Type id from user: "));
    try {
      Connection cn = Connection_DB.connect();
      PreparedStatement pst = cn.prepareStatement(
          "select * from Usuarios where Id_Usuario = " + ID + "");
      ResultSet rs = pst.executeQuery();

      if (rs.next()) {
        flag = true;
        ID = rs.getInt("Id_Usuario");

        txt_Name.setText(rs.getString("Nombre"));
        txt_Name.setEnabled(false);
        txt_mail.setText(rs.getString("email"));
        txt_mail.setEnabled(false);
        txt_Phone.setText(rs.getString("telefono"));
        txt_Phone.setEnabled(false);
        txt_Username.setText(rs.getString("username"));
        txt_Username.setEnabled(false);
        txt_Registered.setText(rs.getString("registrado_por"));
        txt_Registered.setEnabled(false);
        txt_Status.setText(rs.getString("estatus"));
        txt_Status.setEnabled(false);
      } else {
        JOptionPane.showMessageDialog(null, "There isn't user with this ID!");
      }
      cn.close();
    } catch (SQLException e) {
      System.err.println("Failed to load user! " + e);
      JOptionPane.showMessageDialog(null, "Failed to load user!");
    }

  }// GEN-LAST:event_btn_Eliminar1ActionPerformed

  private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_EliminarActionPerformed
    if (flag) {
      try {

        Connection cn = Connection_DB.connect();
        PreparedStatement pst = cn.prepareStatement(
            "delete from Usuarios where Id_Usuario = " + ID + "");
        pst.executeUpdate();

        txt_mail.setBackground(Color.GREEN);
        txt_Username.setBackground(Color.GREEN);
        txt_Name.setBackground(Color.GREEN);
        txt_Phone.setBackground(Color.GREEN);
        JOptionPane.showMessageDialog(null, "Deleted user");
        this.dispose();

      } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Failed to delete user");
        System.err.println("Failed to delete user " + e);
      }
    } else {
      JOptionPane.showMessageDialog(null, "You have to search for a user by id to delete it");
    }

  }// GEN-LAST:event_btn_EliminarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Delete_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Delete_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Delete_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Delete_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Delete_Users().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup STATUS;
  private javax.swing.JButton btn_Eliminar;
  private javax.swing.JButton btn_SearchID;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel_Email;
  private javax.swing.JLabel jLabel_Name;
  private javax.swing.JLabel jLabel_Phone;
  private javax.swing.JLabel jLabel_Registered;
  private javax.swing.JLabel jLabel_Status;
  private javax.swing.JLabel jLabel_Username;
  private javax.swing.JLabel lbl_Titulo;
  private javax.swing.JLabel lbl_wallpaper;
  private javax.swing.JTextField txt_Name;
  private javax.swing.JTextField txt_Phone;
  private javax.swing.JTextField txt_Registered;
  private javax.swing.JTextField txt_Status;
  private javax.swing.JTextField txt_Username;
  private javax.swing.JTextField txt_mail;
  // End of variables declaration//GEN-END:variables
}
