
package windows;
import classes.Connection_DB;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import static windows.Login.user;

public class ID extends javax.swing.JFrame {

    String user;
    public static String user_update = "";
    public  static int Id_Cliente;
    DefaultTableModel model = new DefaultTableModel(); //Modificar tablas

    public ID() {
        initComponents();
        user = Login.user;
        setSize(497, 416);
        setTitle("Client acess - " + user + " session");
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));

        lbl_wallpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection cn = Connection_DB.connect();
            PreparedStatement pst = cn.prepareStatement(
                    "select Id_Usuario, Nombre, username from Usuarios where estatus='Cliente'");
            ResultSet rs = pst.executeQuery();

            jTable_Users = new JTable(model);
            jScrollPane1.setViewportView(jTable_Users);

            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("username");

            while (rs.next()) {

                Object[] fila = new Object[3];
                for (int i = 0; i < 3; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);

            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error filling table." + e);
            JOptionPane.showMessageDialog(null, "Error filling table");
        }

    }
    
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable_Users = new javax.swing.JTable();
    lbl_Titulo = new javax.swing.JLabel();
    lbl_Titulo1 = new javax.swing.JLabel();
    jLabel_Nombre = new javax.swing.JLabel();
    txt_ID = new javax.swing.JTextField();
    btn_Accept = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jScrollPane1.setEnabled(false);

    jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jTable_Users);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 450, 230));

    lbl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    lbl_Titulo.setForeground(new java.awt.Color(255, 255, 255));
    lbl_Titulo.setAlignmentY(0.0F);
    getContentPane().add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 190, 40));

    lbl_Titulo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    lbl_Titulo1.setForeground(new java.awt.Color(255, 255, 255));
    lbl_Titulo1.setText("User Access");
    lbl_Titulo1.setAlignmentY(0.0F);
    getContentPane().add(lbl_Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

    jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Nombre.setText("Enter your ID:");
    getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    txt_ID.setBackground(new java.awt.Color(93, 93, 212));
    txt_ID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_ID.setForeground(new java.awt.Color(255, 255, 255));
    txt_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_ID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, -1));

    btn_Accept.setBackground(new java.awt.Color(93, 93, 212));
    btn_Accept.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btn_Accept.setForeground(new java.awt.Color(255, 255, 255));
    btn_Accept.setText("Accept");
    btn_Accept.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_AcceptActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 180, 35));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Created by Tony ©");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AcceptActionPerformed
        // TODO add your handling code here:
        Id_Cliente=Integer.parseInt(txt_ID.getText());
        try {
            Connection cn = Connection_DB.connect();
            PreparedStatement pst = cn.prepareStatement(
                    "select estatus from Usuarios where Id_Usuario=" +Id_Cliente+"");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Main_Clients interfaz_clientes = new Main_Clients();
        interfaz_clientes.setVisible(true);
        dispose();
            }
        } catch (SQLException e) {
            System.err.println("Error on the accept button" +e);
                JOptionPane.showMessageDialog(null, "Error on the accept button");
        }
        
        
    }//GEN-LAST:event_btn_AcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ID().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Accept;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel_Nombre;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable_Users;
  private javax.swing.JLabel lbl_Titulo;
  private javax.swing.JLabel lbl_Titulo1;
  private javax.swing.JLabel lbl_wallpaper;
  private javax.swing.JTextField txt_ID;
  // End of variables declaration//GEN-END:variables
}
