package windows;

import classes.Connection_DB;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import static windows.Main_Administrator.sesion_usuario;
public class Main_Clients extends javax.swing.JFrame {

    String user, nombre_usuario;
    public static int sesion_usuario;
        public static int Id_cliente;

    public Main_Clients() {
        
        
        initComponents();
        user = Login.user;
        sesion_usuario = 1;

        setSize(435, 262);
        setResizable(false);
        setTitle("Client - " + user + " session");
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));

        lbl_wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection cn = Connection_DB.connect();
            PreparedStatement pst = cn.prepareStatement(
                    "select Nombre from Usuarios where username = '" + user + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                nombre_usuario = rs.getString("Nombre");
                lbl_NombreUsuario.setText("Welcome@ "+nombre_usuario);
            }
        } catch (Exception e) {
            System.err.println("Failed connection from client interface" +e);
        }
        

    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbl_NombreUsuario = new javax.swing.JLabel();
    btn_Shopping = new javax.swing.JButton();
    btn_LogOut = new javax.swing.JButton();
    btn_Orders = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lbl_NombreUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
    lbl_NombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
    lbl_NombreUsuario.setText("jLabel1");
    getContentPane().add(lbl_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    btn_Shopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compra.png"))); // NOI18N
    btn_Shopping.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ShoppingActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Shopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

    btn_LogOut.setBackground(new java.awt.Color(93, 93, 212));
    btn_LogOut.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btn_LogOut.setForeground(new java.awt.Color(255, 255, 255));
    btn_LogOut.setText("Log Out");
    btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_LogOutActionPerformed(evt);
      }
    });
    getContentPane().add(btn_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 150, 35));

    btn_Orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consulta.png"))); // NOI18N
    btn_Orders.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_OrdersActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, 100));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Start shopping");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, -1, -1));

    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Check orders");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Creado por Tony ©");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 270));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_ShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShoppingActionPerformed
        Shopping shopping = new Shopping();
        shopping.setVisible(true);

    }//GEN-LAST:event_btn_ShoppingActionPerformed

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void btn_OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrdersActionPerformed
        Orders order = new Orders();
        order.setVisible(true);
    }//GEN-LAST:event_btn_OrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Clients().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_LogOut;
  private javax.swing.JButton btn_Orders;
  private javax.swing.JButton btn_Shopping;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel lbl_NombreUsuario;
  private javax.swing.JLabel lbl_wallpaper;
  // End of variables declaration//GEN-END:variables
}
