package windows;

import classes.Connection_DB;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

public class Main_Administrator extends javax.swing.JFrame {

  String user, nombre_usuario;
  public static int sesion_usuario;

  public Main_Administrator() {
    initComponents();
    user = Login.user;
    sesion_usuario = 1;

    setSize(662, 432);
    setResizable(false);
    setTitle("Administrator - " + user + " session");
    setLocationRelativeTo(null);

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
    Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
        lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));

    lbl_wallpaper.setIcon(icono);
    this.repaint();

    try {
      Connection cn = Connection_DB.connect();
      PreparedStatement pst = cn.prepareStatement(
          "select Nombre from Usuarios where username = '" + user + "'");

      ResultSet rs = pst.executeQuery();

      if (rs.next()) {
        nombre_usuario = rs.getString("Nombre");
        lbl_User_Name.setText("Welcome@ " + nombre_usuario);
      }
    } catch (Exception e) {
      System.err.println("Connection error from administrator sesion" + e);
    }
  }

  @Override
  public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
    return retValue;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbl_User_Name = new javax.swing.JLabel();
    btn_Register = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    btn_ManageUsers = new javax.swing.JButton();
    btn_DeleteUsers = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    btn_LogOut = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lbl_User_Name.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
    lbl_User_Name.setForeground(new java.awt.Color(255, 255, 255));
    lbl_User_Name.setText("jLabel1");
    getContentPane().add(lbl_User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    btn_Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
    btn_Register.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_RegisterActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Register Users");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, -1, -1));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Developer");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

    btn_ManageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gestionar.png"))); // NOI18N
    btn_ManageUsers.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ManageUsersActionPerformed(evt);
      }
    });
    getContentPane().add(btn_ManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, 100));

    btn_DeleteUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrar.png"))); // NOI18N
    btn_DeleteUsers.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_DeleteUsersActionPerformed(evt);
      }
    });
    getContentPane().add(btn_DeleteUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 120, 100));

    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Manage Users");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 170, -1, -1));

    btn_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrarSesion.png"))); // NOI18N
    btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_LogOutActionPerformed(evt);
      }
    });
    getContentPane().add(btn_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 240, 120, 100));

    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Created by Tony ©");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Delete Users");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 170, -1, -1));

    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Log Out");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 120, 100));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 430));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_ManageUsersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_ManageUsersActionPerformed
    Manage_Users gestionarUsuarios = new Manage_Users();
    gestionarUsuarios.setVisible(true);
    dispose();
  }// GEN-LAST:event_btn_ManageUsersActionPerformed

  private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_RegisterActionPerformed
    Register registro = new Register();
    registro.setVisible(true);
  }// GEN-LAST:event_btn_RegisterActionPerformed

  private void btn_DeleteUsersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_DeleteUsersActionPerformed
    Delete_Users borrarusuarios = new Delete_Users();
    borrarusuarios.setVisible(true);
  }// GEN-LAST:event_btn_DeleteUsersActionPerformed

  private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_CerrarSesionActionPerformed
    Login login = new Login();
    login.setVisible(true);
    dispose();
  }// GEN-LAST:event_btn_CerrarSesionActionPerformed

  private void btn_SitioWebActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_SitioWebActionPerformed
    try {
      Desktop.getDesktop().browse(new URI("http://localhost/Proyecto%20Final/Pagina%20Principal.php"));
    } catch (URISyntaxException ex) {

      System.out.println(ex);

    } catch (IOException e) {

      System.out.println(e);

    }

  }// GEN-LAST:event_btn_SitioWebActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    JLabel label = new JLabel();
    Font font = label.getFont();

    // Create some css from the label's font
    StringBuffer style = new StringBuffer("font-family:" + font.getFamily() + ";");
    style.append("font-weight:" + (font.isBold() ? "bold" : "nomral") + ";");
    style.append("font-size:" + font.getSize() + "pt;");

    // html content
    JEditorPane editorPane = new JEditorPane("text/html", "<html><body style=\"" + style + "\">"
        + "follow me on Github: <a href=\"https://github.com/SoyTonyRodriguez\"> Github </a>"
        + "</body></html>");

    // handle link events
    editorPane.addHyperlinkListener(new HyperlinkListener() {
      @Override
      public void hyperlinkUpdate(HyperlinkEvent e) {
          if(e.getEventType().equals(HyperlinkEvent.EventType.ACTIVATED))
            try {
              Desktop.getDesktop().browse(e.getURL().toURI());
          } catch (IOException ex) {
            Logger.getLogger(Main_Administrator.class.getName()).log(Level.SEVERE, null, ex);
          } catch (URISyntaxException ex) {
            Logger.getLogger(Main_Administrator.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
    });

    editorPane.setEditable(false);
    // editorPane.setBackground(new Color(214, 217, 223));

    // show
    JOptionPane.showMessageDialog(null, editorPane, "About me", JOptionPane.INFORMATION_MESSAGE);

  }// GEN-LAST:event_jButton1ActionPerformed

  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Main_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Main_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Main_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Main_Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main_Administrator().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_DeleteUsers;
  private javax.swing.JButton btn_LogOut;
  private javax.swing.JButton btn_ManageUsers;
  private javax.swing.JButton btn_Register;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel lbl_User_Name;
  private javax.swing.JLabel lbl_wallpaper;
  // End of variables declaration//GEN-END:variables
}
