/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.sql.*;
import classes.Connection_DB;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

/**
 *
 * @author Tony
 */
public class Manage_Users extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Users
     */
    String user;
    public static String user_update = "";
    DefaultTableModel model = new DefaultTableModel(); // Modificar tablas

    public Manage_Users() {
        initComponents();

        user = Login.user;

        setSize(630, 463);
        setTitle("Usuarios registrados - Sesión de " + user);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));

        lbl_wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection cn = Connection_DB.connect();
            PreparedStatement pst = cn.prepareStatement(
                    "select Id_Usuario, Nombre, username, telefono, estatus from Usuarios");
            ResultSet rs = pst.executeQuery();

            jTable_Users = new JTable(model);
            jScrollPane1.setViewportView(jTable_Users);

            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("username");
            model.addColumn("telefono");
            model.addColumn("Estatus");

            while (rs.next()) {

                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);

            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error filling the table" + e);
            JOptionPane.showMessageDialog(null, "Error filling the table!");
        }

        jTable_Users.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_Users.rowAtPoint(e.getPoint());
                int columna_point = 2;

                if (fila_point > -1) {
                    user_update = (String) model.getValueAt(fila_point, columna_point);
                    Users_Information informacion_usuario = new Users_Information();
                    informacion_usuario.setVisible(true);
                }
            }
        });

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable_Users = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    btn_Report = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    btn_Return = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    btn_Refresh = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Registered Users");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

    jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jTable_Users);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 630, 230));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Creado por Tony ©");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

    btn_Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporte.png"))); // NOI18N
    btn_Report.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ReportActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 120, 100));

    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Go Back");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 390, -1, -1));

    btn_Return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volver.png"))); // NOI18N
    btn_Return.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ReturnActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, 100));

    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Create Report");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

    btn_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar.png"))); // NOI18N
    btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_RefreshActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 120, 100));

    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Refresh");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 390, -1, -1));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 460));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_RefreshActionPerformed
        Manage_Users manage = new Manage_Users();
        manage.setVisible(false);
        dispose();
        manage.setVisible(true);

    }// GEN-LAST:event_btn_RefreshActionPerformed

    private void btn_ReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_ReturnActionPerformed
        Main_Administrator main_Window = new Main_Administrator();
        main_Window.setVisible(true);
        dispose();
    }// GEN-LAST:event_btn_ReturnActionPerformed

    private void btn_ReportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_ReportActionPerformed
        Document document = new Document();

        try {
            String directory = System.getProperty("user.home");
            PdfWriter.getInstance(document, new FileOutputStream(directory + "/Desktop/Reporte_Usuarios.pdf"));
            document.open();

            PdfPTable table = new PdfPTable(5);
            table.addCell("ID");
            table.addCell("Nombre");
            table.addCell("USERNAME");
            table.addCell("Telefono");
            table.addCell("Estatus");

            try {
                Connection cn = Connection_DB.connect();
                PreparedStatement pst = cn.prepareStatement(
                        "select Id_Usuario, Nombre, username, telefono, estatus from Usuarios");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    do {
                        table.addCell(rs.getString(1));
                        table.addCell(rs.getString(2));
                        table.addCell(rs.getString(3));
                        table.addCell(rs.getString(4));
                        table.addCell(rs.getString(5));
                    } while (rs.next());
                    document.add(table);
                }

            } catch (DocumentException | SQLException e) {
            }
            document.close();
            JOptionPane.showMessageDialog(null, "Report created");
        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
        }
    }// GEN-LAST:event_btn_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Users.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Users.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Users.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Users.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Users().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Refresh;
  private javax.swing.JButton btn_Report;
  private javax.swing.JButton btn_Return;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable_Users;
  private javax.swing.JLabel lbl_wallpaper;
  // End of variables declaration//GEN-END:variables
}
