/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import classes.Connection_DB;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LE_Alumno-01
 */
public class Orders extends javax.swing.JFrame {

  /**
   * Creates new form Orders
   */
  String user;
  public static String user_update = "";
  int id;
  DefaultTableModel model = new DefaultTableModel(); // Modify tables

  public Orders() {
    initComponents();

    id = ID.Id_Cliente;
    user = Login.user;

    setSize(630, 330);
    setTitle("Orders - " + user + " session");
    setResizable(false);
    setLocationRelativeTo(null);

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
    Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
        lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));

    lbl_wallpaper.setIcon(icono);
    this.repaint();

    try {
      Connection cn = Connection_DB.connect();
      //PreparedStatement pst = cn.prepareStatement(
      //    "select id_pedido, Producto, total from pedidos where Id_Usuario = " + id + ";");
      
      PreparedStatement pst = cn.prepareStatement(
              "select id_pedido, Producto, total from pedidos where id_Usuario=(select "
                      + "Id_Usuario from Usuarios where username = '"+ Login.user + "')");
      ResultSet rs = pst.executeQuery();

      jTable_Orders = new JTable(model);
      jScrollPane1.setViewportView(jTable_Orders);

      model.addColumn("ID");
      model.addColumn("Producto");
      model.addColumn("total");

      while (rs.next()) {

        Object[] fila = new Object[3];
        for (int i = 0; i < 3; i++) {
          fila[i] = rs.getObject(i + 1);
        }
        model.addRow(fila);

      }
      cn.close();

    } catch (SQLException e) {
      System.err.println("Error filling the table" + e);
      JOptionPane.showMessageDialog(null, "Error filling the table");
    }

  }

  @Override
  public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
    return retValue;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable_Orders = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jTable_Orders.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jTable_Orders);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, 230));

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Orders");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 11, -1, -1));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Creado por Tony ©");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 630, 350));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Orders().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable_Orders;
  private javax.swing.JLabel lbl_wallpaper;
  // End of variables declaration//GEN-END:variables
}
