/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import classes.Connection_DB;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Tony
 */
public class Register extends javax.swing.JFrame {

  String user;

  public Register() {
    initComponents();
    user = Login.user;
    setTitle("Register new user - " + user + " session");
    setSize(610, 349);
    setResizable(false);
    setLocationRelativeTo(null);

    ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
    Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_Wallpaper.getWidth(),
        lbl_Wallpaper.getHeight(), Image.SCALE_DEFAULT));

    // Avoid closing the program, when you exit this window
    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    lbl_Wallpaper.setIcon(icono);
    this.repaint();
  }

  @Override
  public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
    return retValue;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    status = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txt_name = new javax.swing.JTextField();
    txt_mail = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    txt_Phone = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txt_username = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txt_password = new javax.swing.JPasswordField();
    btn_Register = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    rdb_Administrador = new javax.swing.JRadioButton();
    rdb_Cliente = new javax.swing.JRadioButton();
    jLabel8 = new javax.swing.JLabel();
    lbl_Wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Register Users");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Status:");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

    txt_name.setBackground(new java.awt.Color(93, 93, 212));
    txt_name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_name.setForeground(new java.awt.Color(255, 255, 255));
    txt_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

    txt_mail.setBackground(new java.awt.Color(93, 93, 212));
    txt_mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_mail.setForeground(new java.awt.Color(255, 255, 255));
    txt_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_mail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Email:");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Phone:");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

    txt_Phone.setBackground(new java.awt.Color(93, 93, 212));
    txt_Phone.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Phone.setForeground(new java.awt.Color(255, 255, 255));
    txt_Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Phone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Username:");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

    txt_username.setBackground(new java.awt.Color(93, 93, 212));
    txt_username.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_username.setForeground(new java.awt.Color(255, 255, 255));
    txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Password:");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

    txt_password.setBackground(new java.awt.Color(93, 93, 212));
    txt_password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_password.setForeground(new java.awt.Color(255, 255, 255));
    txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 210, -1));

    btn_Register.setBackground(new java.awt.Color(93, 93, 212));
    btn_Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
    btn_Register.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_RegisterActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 120, 100));

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Name:");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    status.add(rdb_Administrador);
    rdb_Administrador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    rdb_Administrador.setForeground(new java.awt.Color(255, 255, 255));
    rdb_Administrador.setText("Administrator");
    getContentPane().add(rdb_Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

    status.add(rdb_Cliente);
    rdb_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    rdb_Cliente.setForeground(new java.awt.Color(255, 255, 255));
    rdb_Cliente.setText("Client");
    getContentPane().add(rdb_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Created by Tony ©");
    getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));
    getContentPane().add(lbl_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 349));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_RegisterActionPerformed
    int flag = 0;
    String name, mail, phone, username, pass, status = "";

    name = txt_name.getText().trim();// .trim elimina espacios al inicio y al final
    mail = txt_mail.getText().trim();
    phone = txt_Phone.getText().trim();
    username = txt_username.getText().trim();
    pass = txt_password.getText().trim();
    if (rdb_Cliente.isSelected()) {
      status = "Cliente";
    } else if (rdb_Administrador.isSelected()) {
      status = "Administrador";
    }

    if (mail.equals("")) {
      txt_mail.setBackground(Color.red);
      flag++;
    }
    if (username.equals("")) {
      txt_username.setBackground(Color.red);
      flag++;
    }
    if (pass.equals("")) {
      txt_password.setBackground(Color.red);
      flag++;
    }
    if (name.equals("")) {
      txt_name.setBackground(Color.red);
      flag++;
    }
    if (phone.equals("")) {
      txt_Phone.setBackground(Color.red);
      flag++;
    }
    if (status.equals("")) {
      rdb_Cliente.setBackground(Color.red);
      rdb_Administrador.setBackground(Color.red);
    }

    try {
      Connection cn = Connection_DB.connect();
      PreparedStatement pst = cn.prepareStatement(
          "select username from Usuarios where username = '" + username + "'");
      ResultSet rs = pst.executeQuery();

      if (rs.next()) {
        txt_username.setBackground(Color.red);
        JOptionPane.showMessageDialog(null, "Username not available");
        cn.close();
      } else {

        cn.close();

        if (flag == 0) {
          try {

            Connection cn2 = Connection_DB.connect();
            PreparedStatement pst2 = cn2.prepareStatement(
                "insert into Usuarios values (?,?,?,?,?,?,?,?)");

            // Add values of the database in insert query
            pst2.setInt(1, 0);
            pst2.setString(2, name);
            pst2.setString(3, mail);
            pst2.setString(4, phone);
            pst2.setString(5, username);
            pst2.setString(6, pass);
            pst2.setString(7, status);
            pst2.setString(8, user);

            // Execute the query 
            pst2.executeUpdate();
            cn2.close();

            clear();

            txt_mail.setBackground(Color.GREEN);
            txt_username.setBackground(Color.GREEN);
            txt_password.setBackground(Color.GREEN);
            txt_name.setBackground(Color.GREEN);
            txt_Phone.setBackground(Color.GREEN);
            rdb_Cliente.setBackground(Color.GREEN);
            rdb_Administrador.setBackground(Color.GREEN);

            JOptionPane.showMessageDialog(null, "Successful register");
            this.dispose();

          } catch (SQLException e) {
            System.err.println("Error registering user" + e);
            JOptionPane.showMessageDialog(null, "Error registering user!");

          }
        } else {
          JOptionPane.showMessageDialog(null, "You have to fill all the fields");
          Color color = new Color(93, 93, 212);
          txt_mail.setBackground(color);
          txt_username.setBackground(color);
          txt_password.setBackground(color);
          txt_name.setBackground(color);
          txt_Phone.setBackground(color);
          rdb_Cliente.setBackground(color);
          rdb_Administrador.setBackground(color);
        }
      }
    } catch (SQLException e) {
      System.err.println("Error validating username: " + e);
      JOptionPane.showMessageDialog(null, "¡Error validating username!!");
    }

  }// GEN-LAST:event_btn_RegisterActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Register().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Register;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel lbl_Wallpaper;
  private javax.swing.JRadioButton rdb_Administrador;
  private javax.swing.JRadioButton rdb_Cliente;
  private javax.swing.ButtonGroup status;
  private javax.swing.JTextField txt_Phone;
  private javax.swing.JTextField txt_mail;
  private javax.swing.JTextField txt_name;
  private javax.swing.JPasswordField txt_password;
  private javax.swing.JTextField txt_username;
  // End of variables declaration//GEN-END:variables

  public void clear() {
    txt_mail.setText("");
    txt_name.setText("");
    txt_password.setText("");
    txt_Phone.setText("");
    txt_username.setText("");
  }

}
