/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.sql.*;
import classes.Connection_DB;
import java.awt.Color;
import javax.swing.Icon;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;


public class Reset_Password extends javax.swing.JFrame {

    String user = "", user_update = "";
    
    public Reset_Password() {
        initComponents();
        user = Login.user;
        user_update = Manage_Users.user_update;

        setSize(248, 247);
        setResizable(false);
        setTitle("Change of password " + user_update);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icono);
        this.repaint();
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    pasf_Password = new javax.swing.JPasswordField();
    pasf_Confirmation = new javax.swing.JPasswordField();
    jLabel7 = new javax.swing.JLabel();
    btn_RestaurarPassword = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Reset password");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 10, -1, -1));

    pasf_Password.setBackground(new java.awt.Color(93, 93, 212));
    pasf_Password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    pasf_Password.setForeground(new java.awt.Color(255, 255, 255));
    pasf_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    pasf_Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(pasf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, 210, -1));

    pasf_Confirmation.setBackground(new java.awt.Color(93, 93, 212));
    pasf_Confirmation.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    pasf_Confirmation.setForeground(new java.awt.Color(255, 255, 255));
    pasf_Confirmation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    pasf_Confirmation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(pasf_Confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, 210, -1));

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("New Password:");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    btn_RestaurarPassword.setBackground(new java.awt.Color(93, 93, 212));
    btn_RestaurarPassword.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btn_RestaurarPassword.setText("Reset Password");
    btn_RestaurarPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_RestaurarPasswordActionPerformed(evt);
      }
    });
    getContentPane().add(btn_RestaurarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 35));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Created by Tony ©");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 220, -1, -1));

    jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Confirm Password:");
    getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, -1, -1));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 261));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_RestaurarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RestaurarPasswordActionPerformed
        String password, confirm_Password;

        password = pasf_Password.getText().trim();
        confirm_Password = pasf_Confirmation.getText().trim();

        if (!password.equals("") && !confirm_Password.equals("")) {
            if (password.equals(confirm_Password)) {

                try {
                    Connection cn = Connection_DB.connect();
                    PreparedStatement pst= cn.prepareStatement(
                        "update Usuarios set password=? where username = '"+ user_update+"'");

                    pst.setString(1, password);

                    pst.executeUpdate();
                    cn.close();
                    pasf_Password.setBackground(Color.GREEN);
                    pasf_Confirmation.setBackground(Color.GREEN);

                    JOptionPane.showMessageDialog(null, "Successful restore!");
                    this.dispose();

                } catch (SQLException e) {
                    System.out.println("Errror en restaurar password "+ e);
                    System.out.println("Failed password restore!"+ e);
                }

            } else {
                pasf_Confirmation.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "The passwords have to be the same");
            }

        } else {
            pasf_Password.setBackground(Color.red);
            pasf_Confirmation.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "You can't hava an empty password!");
        }

    }//GEN-LAST:event_btn_RestaurarPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reset_Password().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_RestaurarPassword;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel lbl_wallpaper;
  private javax.swing.JPasswordField pasf_Confirmation;
  private javax.swing.JPasswordField pasf_Password;
  // End of variables declaration//GEN-END:variables
}
