/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import classes.Connection_DB;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Tony
 */
public class Shopping extends javax.swing.JFrame {

  String user, producto;
  int total, quantity_Guittar, quantity_Microphone, quantity_Headphone, total_Guittar, total_Microphone, total_Headphones;
  int id;

  public Shopping() {
    initComponents();
    user = Login.user;
    id = ID.Id_Cliente;
    setTitle("Purchases - " + user + " session");
    setSize(467, 491);
    setResizable(false);
    setLocationRelativeTo(null);

    ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
    Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
        lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    /*
     * Evitamos que el
     * programa se cierre cuando cerramos la interfaz
     */

    lbl_wallpaper.setIcon(icono);
    this.repaint();
    btn_Ok.setEnabled(false);
    txt_guitarr.setEnabled(false);
    txt_guitarr.setText("" + 0);
    txt_Headphones.setEnabled(false);
    txt_Headphones.setText("" + 0);
    txt_microphone.setEnabled(false);
    txt_microphone.setText("" + 0);

    total_Headphones = 0;
    total_Guittar = 0;
    total_Microphone = 0;

  }

  @Override
  public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
    return retValue;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Productos = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    jLabel_Nombre1 = new javax.swing.JLabel();
    jLabel_Nombre3 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtaTerminos = new javax.swing.JTextArea();
    chk_Terms = new javax.swing.JCheckBox();
    btn_Ok = new javax.swing.JButton();
    txt_Headphones = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel_Nombre2 = new javax.swing.JLabel();
    jLabel_Nombre4 = new javax.swing.JLabel();
    jLabel_Nombre6 = new javax.swing.JLabel();
    jLabel_Nombre7 = new javax.swing.JLabel();
    txt_guitarr = new javax.swing.JTextField();
    txt_microphone = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    rdb_Guitarr = new javax.swing.JRadioButton();
    rdb_Microphone = new javax.swing.JRadioButton();
    rdb_Headphones = new javax.swing.JRadioButton();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Customer Purchases");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

    jLabel_Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel_Nombre1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Nombre1.setText("Price :              $300");
    getContentPane().add(jLabel_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 20));

    jLabel_Nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Nombre3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Nombre3.setText("Quantity:");
    getContentPane().add(jLabel_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

    txtaTerminos.setEditable(false);
    txtaTerminos.setBackground(new java.awt.Color(93, 93, 212));
    txtaTerminos.setColumns(20);
    txtaTerminos.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
    txtaTerminos.setForeground(new java.awt.Color(255, 255, 255));
    txtaTerminos.setRows(5);
    txtaTerminos.setText("POLÍTICA DE REEMBOLSO Y GARANTÍA\n\nEn el caso de productos que sean  mercancías irrevocables no-tangibles,\nno realizamos reembolsos después de que se envíe el producto,\nusted tiene la responsabilidad de entender antes de comprarlo. \n Le pedimos que lea cuidadosamente antes de comprarlo. \nHacemos solamente excepciones con esta regla cuando la \ndescripción no se ajusta al producto. Hay algunos productos que \npudieran tener garantía y posibilidad de reembolso pero este será\n especificado al comprar el producto.");
    txtaTerminos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Terminos y Condiciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
    jScrollPane1.setViewportView(txtaTerminos);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 440, 210));

    chk_Terms.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    chk_Terms.setForeground(new java.awt.Color(255, 255, 255));
    chk_Terms.setText("Accept Terms and Conditions");
    chk_Terms.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chk_TermsActionPerformed(evt);
      }
    });
    getContentPane().add(chk_Terms, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 230, -1));

    btn_Ok.setBackground(new java.awt.Color(93, 93, 212));
    btn_Ok.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btn_Ok.setForeground(new java.awt.Color(255, 255, 255));
    btn_Ok.setText("Ok");
    btn_Ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_OkActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

    txt_Headphones.setBackground(new java.awt.Color(93, 93, 212));
    txt_Headphones.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Headphones.setForeground(new java.awt.Color(255, 255, 255));
    txt_Headphones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Headphones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Headphones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 70, 20));

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Product:");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    jLabel_Nombre2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Nombre2.setText("Price :              $900");
    getContentPane().add(jLabel_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 20));

    jLabel_Nombre4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel_Nombre4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Nombre4.setText("Price :              $400");
    getContentPane().add(jLabel_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 20));

    jLabel_Nombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Nombre6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Nombre6.setText("Quantity:");
    getContentPane().add(jLabel_Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

    jLabel_Nombre7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Nombre7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Nombre7.setText("Quantity:");
    getContentPane().add(jLabel_Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

    txt_guitarr.setBackground(new java.awt.Color(93, 93, 212));
    txt_guitarr.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_guitarr.setForeground(new java.awt.Color(255, 255, 255));
    txt_guitarr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_guitarr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_guitarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 70, 20));

    txt_microphone.setBackground(new java.awt.Color(93, 93, 212));
    txt_microphone.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_microphone.setForeground(new java.awt.Color(255, 255, 255));
    txt_microphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_microphone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_microphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 70, 20));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Creado por Tony ©");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

    Productos.add(rdb_Guitarr);
    rdb_Guitarr.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    rdb_Guitarr.setForeground(new java.awt.Color(255, 255, 255));
    rdb_Guitarr.setText("Guitarra");
    rdb_Guitarr.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rdb_GuitarrActionPerformed(evt);
      }
    });
    getContentPane().add(rdb_Guitarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

    Productos.add(rdb_Microphone);
    rdb_Microphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    rdb_Microphone.setForeground(new java.awt.Color(255, 255, 255));
    rdb_Microphone.setText("Microfono");
    rdb_Microphone.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rdb_MicrophoneActionPerformed(evt);
      }
    });
    getContentPane().add(rdb_Microphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

    Productos.add(rdb_Headphones);
    rdb_Headphones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    rdb_Headphones.setForeground(new java.awt.Color(255, 255, 255));
    rdb_Headphones.setText("Audifonos");
    rdb_Headphones.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rdb_HeadphonesActionPerformed(evt);
      }
    });
    getContentPane().add(rdb_Headphones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

    lbl_wallpaper.setForeground(new java.awt.Color(255, 255, 255));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 490));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void chk_TermsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chk_TermsActionPerformed
    if (chk_Terms.isSelected()) {
      btn_Ok.setEnabled(true);
    } else {
      btn_Ok.setEnabled(false);
    }

  }// GEN-LAST:event_chk_TermsActionPerformed

  private void btn_OkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_OkActionPerformed
    quantity_Guittar = Integer.parseInt(txt_guitarr.getText());
    quantity_Headphone = Integer.parseInt(txt_Headphones.getText());
    quantity_Microphone = Integer.parseInt(txt_microphone.getText());
    total_Guittar = quantity_Guittar * 900;
    total_Microphone = quantity_Microphone * 400;
    total_Headphones = quantity_Headphone * 300;

    try {
      total = total_Headphones + total_Guittar + total_Microphone;
      JOptionPane.showMessageDialog(null, "Your purchase total is:   " + total);
      this.dispose();
      Connection cn2 = Connection_DB.connect();

      PreparedStatement pst2 = cn2.prepareStatement(
          "insert into pedidos values (?,?,?, (select Id_Usuario from Usuarios where username = '" + Login.user + "'))");
      
      // Este metodo se utiliza para colocarle valores a la base de datos
      pst2.setInt(1, 0);
      pst2.setString(2, producto);
      pst2.setInt(3, total);
      //pst2.setInt(4, id);
      // Nos permite ejecutar las lineas de codigo que le mandamos a la base de datos
      pst2.executeUpdate();
      cn2.close();

      JOptionPane.showMessageDialog(null, "Successfull register");
      this.dispose();

    } catch (SQLException e) {
      System.err.println("Failed register" + e);
      JOptionPane.showMessageDialog(null, "Failed register");

    }

  }// GEN-LAST:event_btn_OkActionPerformed

  private void rdb_GuitarrActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdb_GuitarrActionPerformed
    // TODO add your handling code here:
    if (rdb_Guitarr.isSelected()) {
      txt_guitarr.setEnabled(true);
      producto = "Guitarra";
    } else {
      txt_guitarr.setEnabled(false);
      producto = "";
    }
  }// GEN-LAST:event_rdb_GuitarrActionPerformed

  private void rdb_MicrophoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdb_MicrophoneActionPerformed
    // TODO add your handling code here:
    if (rdb_Microphone.isSelected()) {
      txt_microphone.setEnabled(true);
      producto = "Microfono";
    } else {
      txt_microphone.setEnabled(false);
      producto = "";
    }
  }// GEN-LAST:event_rdb_MicrophoneActionPerformed

  private void rdb_HeadphonesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdb_HeadphonesActionPerformed
    // TODO add your handling code here:
    if (rdb_Headphones.isSelected()) {
      txt_Headphones.setEnabled(true);
      producto = "Audifonos";
    } else {
      txt_Headphones.setEnabled(false);
      producto = "";
    }

  }// GEN-LAST:event_rdb_HeadphonesActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Shopping().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup Productos;
  private javax.swing.JButton btn_Ok;
  private javax.swing.JCheckBox chk_Terms;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel_Nombre1;
  private javax.swing.JLabel jLabel_Nombre2;
  private javax.swing.JLabel jLabel_Nombre3;
  private javax.swing.JLabel jLabel_Nombre4;
  private javax.swing.JLabel jLabel_Nombre6;
  private javax.swing.JLabel jLabel_Nombre7;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbl_wallpaper;
  private javax.swing.JRadioButton rdb_Guitarr;
  private javax.swing.JRadioButton rdb_Headphones;
  private javax.swing.JRadioButton rdb_Microphone;
  private javax.swing.JTextField txt_Headphones;
  private javax.swing.JTextField txt_guitarr;
  private javax.swing.JTextField txt_microphone;
  private javax.swing.JTextArea txtaTerminos;
  // End of variables declaration//GEN-END:variables
}
