/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.sql.*;
import classes.Connection_DB;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class Users_Information extends javax.swing.JFrame {

  String user = "", user_update = "";
  int ID;

  public Users_Information() {
    initComponents();

    user = Login.user;
    user_update = Manage_Users.user_update;

    setSize(623, 352);
    setResizable(false);
    setTitle("Information of " + user_update + " - " + user + " session");
    setLocationRelativeTo(null);

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
    Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
        lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
    lbl_wallpaper.setIcon(icono);
    this.repaint();

    jLabel_Titulo.setText("User information " + user_update);

    try {
      Connection cn = Connection_DB.connect();
      PreparedStatement pst = cn.prepareStatement(
          "select * from Usuarios where username = '" + user_update + "'");
      ResultSet rs = pst.executeQuery();

      if (rs.next()) {
        ID = rs.getInt("Id_Usuario");

        txt_Name.setText(rs.getString("Nombre"));
        txt_mail.setText(rs.getString("email"));
        txt_Phone.setText(rs.getString("telefono"));
        txt_Username.setText(rs.getString("username"));
        txt_Registered.setText(rs.getString("registrado_por"));
        txt_Registered.setEnabled(false);
        txt_Password.setText(rs.getString("password"));
        txt_Password.setEnabled(false);
        if (rdb_Administrator.isSelected()) {
          rs.getString("estatus");
        }
        if (rdb_Client.isSelected()) {
          rs.getString("estatus");
        }
      }
      cn.close();
    } catch (SQLException e) {
      System.err.println("Error loading user. " + e);
      JOptionPane.showMessageDialog(null, "Error loading user");
    }
  }

  @Override
  public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
    return retValue;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    status = new javax.swing.ButtonGroup();
    jLabel_Titulo = new javax.swing.JLabel();
    jLabel_Name = new javax.swing.JLabel();
    txt_Name = new javax.swing.JTextField();
    jLabel_Email = new javax.swing.JLabel();
    txt_mail = new javax.swing.JTextField();
    jLabel_Pass = new javax.swing.JLabel();
    txt_Registered = new javax.swing.JTextField();
    jLabel_Username = new javax.swing.JLabel();
    txt_Username = new javax.swing.JTextField();
    jLabel_Status = new javax.swing.JLabel();
    rdb_Administrator = new javax.swing.JRadioButton();
    rdb_Client = new javax.swing.JRadioButton();
    btn_Update = new javax.swing.JButton();
    btn_Reset_Pass = new javax.swing.JButton();
    jLabel_By = new javax.swing.JLabel();
    txt_Password = new javax.swing.JTextField();
    jLabel_Phone = new javax.swing.JLabel();
    txt_Phone = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    lbl_wallpaper = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Titulo.setText("User information");
    getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 10, -1, -1));

    jLabel_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Name.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Name.setText("Name:");
    getContentPane().add(jLabel_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

    txt_Name.setBackground(new java.awt.Color(93, 93, 212));
    txt_Name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Name.setForeground(new java.awt.Color(255, 255, 255));
    txt_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

    jLabel_Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Email.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Email.setText("Email:");
    getContentPane().add(jLabel_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

    txt_mail.setBackground(new java.awt.Color(93, 93, 212));
    txt_mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_mail.setForeground(new java.awt.Color(255, 255, 255));
    txt_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_mail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

    jLabel_Pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Pass.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Pass.setText("Password:");
    getContentPane().add(jLabel_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

    txt_Registered.setBackground(new java.awt.Color(93, 93, 212));
    txt_Registered.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Registered.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Registered.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Registered, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

    jLabel_Username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Username.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Username.setText("Username:");
    getContentPane().add(jLabel_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

    txt_Username.setBackground(new java.awt.Color(93, 93, 212));
    txt_Username.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Username.setForeground(new java.awt.Color(255, 255, 255));
    txt_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

    jLabel_Status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Status.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Status.setText("Status:");
    getContentPane().add(jLabel_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

    status.add(rdb_Administrator);
    rdb_Administrator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    rdb_Administrator.setForeground(new java.awt.Color(255, 255, 255));
    rdb_Administrator.setText("Administrator");
    getContentPane().add(rdb_Administrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

    status.add(rdb_Client);
    rdb_Client.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    rdb_Client.setForeground(new java.awt.Color(255, 255, 255));
    rdb_Client.setText("Client");
    getContentPane().add(rdb_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

    btn_Update.setBackground(new java.awt.Color(93, 93, 212));
    btn_Update.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btn_Update.setForeground(new java.awt.Color(255, 255, 255));
    btn_Update.setText("Update User");
    btn_Update.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_UpdateActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 210, 35));

    btn_Reset_Pass.setBackground(new java.awt.Color(93, 93, 212));
    btn_Reset_Pass.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btn_Reset_Pass.setForeground(new java.awt.Color(255, 255, 255));
    btn_Reset_Pass.setText("Reset Password");
    btn_Reset_Pass.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_Reset_PassActionPerformed(evt);
      }
    });
    getContentPane().add(btn_Reset_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 210, 35));

    jLabel_By.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_By.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_By.setText("Registered by:");
    getContentPane().add(jLabel_By, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

    txt_Password.setBackground(new java.awt.Color(93, 93, 212));
    txt_Password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Password.setForeground(new java.awt.Color(255, 255, 255));
    txt_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, -1));

    jLabel_Phone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel_Phone.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Phone.setText("Phone:");
    getContentPane().add(jLabel_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

    txt_Phone.setBackground(new java.awt.Color(93, 93, 212));
    txt_Phone.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    txt_Phone.setForeground(new java.awt.Color(255, 255, 255));
    txt_Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txt_Phone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    getContentPane().add(txt_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Created by Tony ©");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));
    getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 360));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_UpdateActionPerformed
    int validation = 0;
    String name, mail, phone, username, status = "";

    mail = txt_mail.getText().trim();
    username = txt_Username.getText().trim();
    name = txt_Name.getText().trim();
    phone = txt_Password.getText().trim();

    if (mail.equals("")) {
      txt_mail.setBackground(Color.red);
      validation++;
    }
    if (username.equals("")) {
      txt_Username.setBackground(Color.red);
      validation++;
    }
    if (name.equals("")) {
      txt_Name.setBackground(Color.red);
      validation++;
    }
    if (phone.equals("")) {
      txt_Password.setBackground(Color.red);
      validation++;
    }

    if (rdb_Client.isSelected()) {
      status = "Cliente";
    } else if (rdb_Administrator.isSelected()) {
      status = "Administrador";
    }

    if (validation == 0 && status != "") {

      try {

        Connection cn = Connection_DB.connect();
        PreparedStatement pst = cn.prepareStatement(
            "select username from Usuarios where username = '" + username + "' and not Id_Usuario = '" + ID + "'");
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

          txt_Username.setBackground(Color.red);
          JOptionPane.showMessageDialog(null, "Username not available");
          cn.close();

        } else {
          Connection cn2 = Connection_DB.connect();
          PreparedStatement pst2 = cn2.prepareStatement(
              "update Usuarios set Nombre=?, email=?, telefono=?, username=?, estatus=? "
                  + "where Id_Usuario = '" + ID + "'");

          pst2.setString(1, name);
          pst2.setString(2, mail);
          pst2.setString(3, phone);
          pst2.setString(4, username);
          pst2.setString(5, status);

          pst2.executeUpdate();
          cn2.close();

          JOptionPane.showMessageDialog(null, "Succesful update");
          dispose();
        }

      } catch (SQLException e) {
        System.err.println("Failed to update " + e);
      }

    } else {
      JOptionPane.showMessageDialog(null, "You have to fill all the fields");
    }

  }// GEN-LAST:event_btn_UpdateActionPerformed

  private void btn_Reset_PassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_Reset_PassActionPerformed
    Reset_Password reset_Password = new Reset_Password();
    reset_Password.setVisible(true);
    dispose();
  }// GEN-LAST:event_btn_Reset_PassActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Users_Information.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Users_Information.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Users_Information.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Users_Information.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Users_Information().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Reset_Pass;
  private javax.swing.JButton btn_Update;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel_By;
  private javax.swing.JLabel jLabel_Email;
  private javax.swing.JLabel jLabel_Name;
  private javax.swing.JLabel jLabel_Pass;
  private javax.swing.JLabel jLabel_Phone;
  private javax.swing.JLabel jLabel_Status;
  private javax.swing.JLabel jLabel_Titulo;
  private javax.swing.JLabel jLabel_Username;
  private javax.swing.JLabel lbl_wallpaper;
  private javax.swing.JRadioButton rdb_Administrator;
  private javax.swing.JRadioButton rdb_Client;
  private javax.swing.ButtonGroup status;
  private javax.swing.JTextField txt_Name;
  private javax.swing.JTextField txt_Password;
  private javax.swing.JTextField txt_Phone;
  private javax.swing.JTextField txt_Registered;
  private javax.swing.JTextField txt_Username;
  private javax.swing.JTextField txt_mail;
  // End of variables declaration//GEN-END:variables
}
